    <?php

        //This will remove the generated span in contact form 7

       add_filter('wpcf7_form_elements', function($content) {
        $content = preg_replace('/<(span).*?class="\s*(?:.*\s)?wpcf7-form-control-wrap(?:\s[^"]+)?\s*"[^\>]*>(.*)<\/\1>/i', '\2', $content);
        return $content;
    });

        //This will add reqiured boolean attribute in input tag generated by contact form 7
        //for css purposes

    add_filter( 'wpcf7_form_elements', 'dd_wpcf7_form_elements_replace' );
    function dd_wpcf7_form_elements_replace( $contentRequired ) {
        // $name == Form Tag Name [textarea* your-message] 
        $name = 'name="fullname"';

        $str_pos = strpos( $contentRequired, $name);
        if (false !== $str_pos) {
            $contentRequired = substr_replace( $contentRequired, ' required="required" ', $str_pos, 0 );
        }
        return $contentRequired;
    }

    
    add_filter( 'wpcf7_form_elements', 'grad_level' );
    function grad_level( $contentGradeLevel ) {
        // $name == Form Tag Name [textarea* your-message] 
        $grade = 'name="grade-level"';

        $str_pos = strpos( $contentGradeLevel, $grade);
        if (false !== $str_pos) {
            $contentGradeLevel = substr_replace( $contentGradeLevel, ' required="required" ', $str_pos, 0 );
        }
        return $contentGradeLevel;
    }

    add_filter( 'wpcf7_form_elements', 'email' );
    function email( $contentEmail ) {
        // $name == Form Tag Name [textarea* your-message] 
        $email = 'name="email"';

        $str_pos = strpos( $contentEmail, $email);
        if (false !== $str_pos) {
            $contentEmail = substr_replace( $contentEmail, ' required="required" ', $str_pos, 0 );
        }
        return $contentEmail;
    }

    add_filter( 'wpcf7_form_elements', 'contactNumber' );
    function contactNumber( $contentContactNumber ) {
        // $name == Form Tag Name [textarea* your-message] 
        $number = 'name="number"';

        $str_pos = strpos( $contentContactNumber, $number);
        if (false !== $str_pos) {
            $contentContactNumber = substr_replace( $contentContactNumber, ' required="required" ', $str_pos, 0 );
        }
        return $contentContactNumber;
    }

    add_filter( 'wpcf7_form_elements', 'yourMessage' );
    function yourMessage( $contentMessage ) {
        // $name == Form Tag Name [textarea* your-message] 
        $message = 'name="message"';

        $str_pos = strpos( $contentMessage, $message);
        if (false !== $str_pos) {
            $contentMessage = substr_replace( $contentMessage, ' required="required" ', $str_pos, 0 );
        }
        return $contentMessage;
    }

    add_filter( 'wpcf7_form_elements', 'contentSubject' );
    function contentSubject( $contentSubject ) {
        // $name == Form Tag Name [textarea* your-message] 
        $message = 'name="your-subject"';

        $str_pos = strpos( $contentSubject, $message);
        if (false !== $str_pos) {
            $contentSubject = substr_replace( $contentSubject, ' required="required" ', $str_pos, 0 );
        }
        return $contentSubject;
    }

